### ISSUE TITLE
Remaining Markup Semantics 

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#10]
## Markup ideas:
- Implement a subset of Markdown
- Custom tags for linking to characters, stories, users, and 'wiki' articles
- OOC comments
### Markdown

```
# Header 1 #
## Header 2 ##
[Link Description](Actual Link)
*italic*
**bold**
  * list
```
### Custom Tags
- character:lexz
- story:lantern_in_the_snow
- entry:117
- member:ethereal_panda
- riiga:wiki_artical_name
### OOC Comment

```
Here I make an inline [This is my out of character comment] comment.
```

Becomes:

```
Here I make an inline [1] comment.

---
[1] This is my out of character comment
```

**Comment by bheiskell** [comment]
I completed this issue except headers, http links, and ordered lists.

The inline comment actually becomes a abbr tag which you can hover over. I think JavaScript will actually make this more fancy at some point, but I say this is done for now.

**Comment by Treijim** [comment]
If this is the place to put this:
I had an idea about story OOC notes. A user can write public/private notes for an entire story via a button similar to "post a new entry" but more like "modify public/private ooc notes" which brings the member to a page with two text fields. One is for notes which are for anybody in the thread, and the other is just for that user. 

When posting a new entry, there is a button to show or hide an extra field which displays all of the public notes (since they can't post an entry on a story they aren't a part of) and all the private notes for that relating user. It would be very useful to put things like brief character descriptions for stories with multiple characters, plot ideas, important things the characters need to remember, and other pieces of information which should be immediately available when making a new post.
