### ISSUE TITLE
Error: Submitted Characters

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#101]
I tried to view characters at the bottom of the characters page, under Pending Characters here: http://riiga.net/characters/view but I received this error: 

Error: The requested address '/characters/view' was not found on this server.

**Comment by bheiskell** [comment]
NOTE: Do not edit other user's characters. There seems to be a bug that causes you to take ownership. I'll resolve both of these bugs together.

**Comment by bheiskell** [comment]
Resolves the issue where an edited character could not be viewed in order to approve. Also, admins are no longer allowed to edit user&#39;s characters. This is a feature loss until PM requests it. Fixed the approve message to inform the admin to go to the adimin character page instead of the bottom of the standard characters page. Lastly, fixed a validation error that didn&#39;t propogate back to the user due to the way the pending behavior works.

Closed by 2f794d87d8eee044b51adb8e9f3fd06238d33d9a

**Comment by bheiskell** [comment]
Note, I also approved all your pending character changes.
