### ISSUE TITLE
Post Deletion Without Prompting

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#105]
Probably needs some kind of safe guard prompt: "Are you sure you want to delete this post?" 

Same applies to other things like leaving stories and removing characters, though, granted, they are far easier to reverse. The potential for a huge post to be deleted with one accidental click is scary.

**Comment by bheiskell** [comment]
I agree. I unfortunately did that part all wrong. It's also susceptible to something called a cross site request forgery as well. That means I could stand up a page that caused you to delete every post from the forum (nasty stuff).

The reason I haven't fixed it is because it's a tiny bit time consuming to back track and fix it. I will add some basic prevention though before I release. I'm making this the last change for 0.1 release.

**Comment by bheiskell** [comment]
Although it doesn&#39;t solve all the CSRFs around, the delete now has a intermediary page that asks are you sure. I think at some point this should actually display the text, but deleting should be rare enough that it&#39;s not too big of a deal. Besides, we only deactivate the entries, not actually delete them ;-) Closed by e17f4ea3a04b28f5c6a5d015e6ff75de21706994
