### ISSUE TITLE
Removing other Characters

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#106]
I can remove somebody else's character from a story. I don't quite get why I would want to do that.

**Comment by bheiskell** [comment]
It's a moderator functionality. Use case: I have an open story, and a person I don't like joins. The only way to kick them out of the story is to make it invite only and eject him from the story. Membership of a story is determined by having a character in the story. Hence, being allowed to remove the character.

You are not however allowed to add one of their characters into a story as this could be abused.

As a side note, in existing stories every current member is a moderator. I could change this so that it's only the first person to post.

**Comment by Treijim** [comment]
Ah okay. So does that mean stories may be invite-only? I forgot to look for that function. 

It depends what a moderator is able to do.

**Comment by bheiskell** [comment]
Invite only is a feature that will be in 0.2.

Moderators can:
- Delete / edit entries
- Change things about a story like invite only status or the location
- Invite people to a story
- Remove characters or people from a story
- Any other features we want them to have

**Comment by bheiskell** [comment]
PM look over this again and verify that this is the way you want it. For now, closing.
