### ISSUE TITLE
Data Import Sanity Checks

### ISSUE THREAD

**Issue by bheiskell** [bheiskell/Riiga#68]
Generic issue to check data import.

**Comment by bheiskell** [comment]
These are the story names, their locations, and the number of posts in the story:
http://etherealpanda.com/misc/files/riiga/story_import_stats.txt

I'm importing 2921 story posts.

The old forum count is 3459, but there are 544 in general, which subtracted results in 2915. This would imply that I'm importing too many story posts, but the first post in a thread doesn't count towards the post count. There are 82 story topics which bums up the count to 3003. Of those topics 49 are thread moves. This means I'm missing 33 posts somewhere.

This doesn't actually mean I'm missing anything. It could be either a math error on my part or not accounting for something.

**Comment by bheiskell** [comment]
There appears to be no "Hyrvea" location. Should I map that to East Riiga?
"Juralua" is also missing. Should I map that to Iyakel?

**Comment by bheiskell** [comment]
These users never used these characters:
koebrugge - Brett Ean
nomlett - Krachticae Inordu
acwbdt - Jacob
Servant - Servant
kuchinawa - Kuchinawa

Can I ignore them? If not, who owns these that have posted.

**Comment by bheiskell** [comment]
Races found:
Fanoran
God
Gruitin
Hamakro
Human
Ildemin
Karithia
Keid
Sirin
Trueblood

What is Phoebe Albridge's race? I'm defaulting it to human unless you say otherwise.

Only new one in the list is God. Should I create a new level 7 race called God? Or should I not import those characters?

**Comment by bheiskell** [comment]
Where should I default each race to live?

**Comment by Treijim** [comment]
I'll create Hyrvea. Is the location creation widget still functioning? Map Juralua to Iyakel.

Ignore characters which haven't been used. This would probably mean those members will become deactivated or ignored since they never technically posted. 

Phoebe is human. 

Karithia should be Karithian. It's probably a typo. Don't create any character listed as a God. 

Default Fanorans to Jindiara, Gruitin to North Tasif, Hamakro to Iyakel, Human to North Tasif, Ildemin to South Ideitess, Karithian to South Nidonn, Keid to omnom. I mean Jindiara. Sirin to East Huirnon, and Truebloods to East Huirnon. 

We'll discuss the numbers problem via msn.

**Comment by bheiskell** [comment]
Special cases handled. Import completed.
