### ISSUE TITLE
Logged in "forever"

### ISSUE THREAD

**Issue by Treijim** [bheiskell/Riiga#91]
I don't remember if we've talked about this. I like to stay logged in; getting timed out is annoying. Can we have an option to do this?

Low priority.

**Comment by bheiskell** [comment]
I agree. I'm not exactly certain how to enforce this. I'll look into it.

**Comment by bheiskell** [comment]
Extended the logout time to one year. Turned security down to the low setting as every feature high triggers causes problems for us. Added a new security component that essentially ignores form expirations, because we really don&#39;t need that. (Technically will expire a loaded form after seven days, but that should be enough right?) Closed by 1d6e82c2712b66212df27c1fd9f15e6043d77b07 Closed by 1d6e82c2712b66212df27c1fd9f15e6043d77b07
